name = "VAN"
uuid = "255db3ff-4450-4718-8808-f69314201519"
authors = ["Lei Wang <wangleiphy@gmail.com>"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
